Duke-MatSci/materialsmine

app/tests/unit/pages/nanomine/howto.spec.js
app/tests/unit/pages/nanomine/news.spec.js
app/tests/unit/pages/nanomine/teams.spec.js

fix(#101): Refactor tests to use new createWrapper
Refactored tests to remove repeated setup code and use new consistent
`createWrapper`. Also suppressed `console.log` calls in howto tests

#101: Refactor tests to use new createWrapper

---

app/src/assets/css/abstract/_variables.scss
app/src/assets/css/modules/_utility.scss
app/src/components/Dialog.vue
app/tests/unit/components/dialog.spec.js

Migrated dialog box styling from whyis
Added named slots for title, content, and actions (e.g., button to close) to facilitate standardized styling
Updated tests in `dialog.spec.js`
close #104

#104: Add styling to dialog boxes

---

.gitignore
resfulservice/package.json
resfulservice/src/middlewares/globalMiddleware.js
resfulservice/src/middlewares/loggerService.js
resfulservice/src/server.js

- All middleware services that are needed globally are now moved into src/middleware/globalMiddleware.js file and then imported into server.js file
- Remove all middlewares from server.js
- Added a global logger service. The new logger is appended to the request header automatically and can be retrieved from any route or module.
- Added Winston to package.json and removed gitignored log files.
close #85

feat(#85): Create logger service - restful

---

app/src/modules/sparql.js
app/src/modules/vega-chart.js
app/src/pages/explorer/sample/sample.js

- Fix exports in sparql.js
- Change `parseSparql` capitalization to match `querySparql`
- Remove `transformSparqlData` from vega-chart.js since its functionality is duplicated by `parseSparql`
- Modify `parseSparql` to look more like `transformSparqlData` did (e.g., change for loop)
Close #123

#123 Refactor sparql.js

---

app/src/pages/explorer/parameterized-query/parameterized-query-page.vue

fix #205 
Address the bug where the parameterized query page couldn't be opened in safari

#205: Recommendation for regex fix for safari

---

app/src/modules/metamine/metamaterial-vegalite.js
app/src/pages/metamine/visualization/metamaterial-plot.js

- Combine the timeout calls into one function
- Remove the unused vega-lite component (we're using a different method to embed the chart)
- Remove `width: 'container'` from the vega spec -- doesn't actually affect width and causes a warning to be thrown
Using the same branch as the original PR 
close #259

Metamine visualization tool: #259 combine timeouts

---

resfulservice/spec/graphql/resolver/dataset.spec.js
resfulservice/src/graphql/resolver/dataset/mutation.js
resfulservice/src/graphql/transformer/datasets.js
resfulservice/src/models/pixelated.js

[Hotfix] #229: Fixed datasetId mutation bug

---

app/src/main.js
app/src/modules/gql/apolloClient.js

Separate apolloClient into its own module. Current version works with Vuex actions, but still requires cache and link (error below)
Note that omitting link and cache from `new ApolloClient` results in the following error: 
```
In order to initialize Apollo Client, you must specify 'link' and 'cache' properties in the options object.
These options are part of the upgrade requirements when migrating from Apollo Client 1.x to Apollo Client 2.x.
For more information, please visit: https://www.apollographql.com/docs/tutorial/client.html#apollo-client-setup
```
close #275

#275: Separate apolloClient into module

---

app/src/pages/explorer/parameterized-query/parameterized-query-page.vue

Fixed the issue where Data Voyager is opened in a new tab (e.g., when the button in the parameterized query UI is clicked), and the data does not get passed correctly and instead only provides the default query data.
closes #224

#224: Update datavoyager link to use button

---

.github/workflows/ci.yml

fix(ci/cd): Fix QA CI pipeline bug

---

.github/workflows/prodci.yml

The current download artifact action is failing. Including the latest version published. This change seeks to fix that by using a different action package.

fix(CI/CD): Pipeline failure

---

.github/workflows/ci.yml

BREAKING CHANGE: The docker image requires the next version from CI. If missing it triggers an error.

build(ci/cd): Fix failing builds-prod

---

.github/workflows/prodci.yml

This update fixed failed restful servicer docker image tagging.

Fix(CI/CD): Update restful service CI image tagging

---

docker-compose.test.git.yml
resfulservice/src/controllers/adminController.js
resfulservice/src/controllers/kgWrapperController.js

This fixes bulk import issues. WHYIS currently has a limit on response. This fix ensures we can get all data for caching for a given instance.

Fix(chore): Kg instance limit hotfix

---

app/src/App.vue
app/src/assets/css/modules/_pages.scss
app/src/assets/css/modules/_utility.scss
app/src/components/Drawer.vue
app/src/components/explorer/Pagination.vue
app/src/pages/CountDown.vue
app/src/pages/explorer/curate/validlist/UpdateXlsList.vue
app/src/pages/explorer/curate/validlist/XlsList.vue
app/src/pages/explorer/curate/validlist/XlsListAll.vue
app/src/pages/nanomine/Home/Home.vue
app/tests/unit/app.spec.js
app/tests/unit/pages/countdown.spec.js
app/tests/unit/pages/nanomine/home.spec.js

Fix the countdown page design bugs for smaller screens and also issues where users can still access the initial pages deployed on prod. 
Updated the drawer and group menu links into appropriate sections.
closes #362

#362 countdown page and drawer fix

---

app/src/modules/queries/sampleQueries.js
app/src/modules/vega-chart.js

Some of the sample queries were causing Fuseki to crash. This PR refactors each of those queries
- Moved all `VALUES` bindings to the beginning of queries, both for samples and also for the individual chart query
- Some triples in the processing steps query needed to be moved into the `OPTIONAL` clause
- Made the `OPTIONAL` nested
Fixes #366

fix(#366): Refactor inefficient sample queries

---

app/src/components/explorer/SearchResultsTable.vue
app/src/modules/vega-chart.js

This fixes vega-chart.js passing the wrong arg for loading purl charts
Also fixes explorer charts that were not properly loading thumbnails

fix(frontend): update chart links in explorer

---

app/src/components/explorer/yasqe.vue
app/src/pages/explorer/chart/editor/Chart.vue
app/src/pages/explorer/parameterized-query/parameterized-query-page.vue

This PR fixes the error where new charts were returning the wrong SPARQL query (and therefore appearing blank).
Yasqe was only returning the **query response** and not the properly synced **query value** to chart editor UI, so all newly created charts were saving with the default query (even though they may have looked correct while still in the editor). It now passes back the correct, updated query whenever a query is run. 
Also temporarily disables `showBtns` arg in the parameterized query yasqe, since that button doesn't currently work with the other existing "run query" button
Definitely works on my local system, but I would strongly recommend testing it on other builds.
This PR does NOT currently fix the error where only one chart is shown at a time in the gallery.

fix(frontend): refactor yasqe to pass queries to chart editor

---

app/src/assets/css/modules/_utility.scss
app/src/components/nanomine/ImageUpload.vue
app/src/modules/vega-chart.js
app/src/pages/explorer/Gallery.vue
app/src/pages/explorer/chart/editor/Chart.vue
app/src/pages/explorer/chart/view/vega-view-script.js
app/src/pages/explorer/chart/view/vega-view.html
app/src/router/module/explorer.js
app/src/store/modules/auth/actions.js
app/src/store/modules/auth/mutations.js
app/src/store/modules/explorer/curation/actions.js
docker-compose.yml
resfulservice/config/constant.js
resfulservice/src/controllers/adminController.js
resfulservice/src/controllers/authController.js
resfulservice/src/utils/elasticSearch.js

Fixes multiple issues with charts:
- Make charts editable from both their individual pages and the gallery
- Allow admins to delete charts (with dialog box confirmation)
- Fix the issue where elastic search would delete all charts from cache instead of just the exact match
- Standardize chart URIs to be consistent with previous implementation
- Make sure shareable chart links are permanent
- Add `(.*)` to chart routes for backwards compatibility with any purl.org charts left on QA (since otherwise Vue router misinterprets `/` symbols in URIs)
fixes #373 #372 
closes #374 (open PR that has been merged into this one)

#373 fix chart editing and deletion

---

app/jest.config.js
resfulservice/.gitignore
resfulservice/config/xlsx.json
resfulservice/package.json
resfulservice/spec/controllers/curationController.spec.js
resfulservice/spec/graphql/resolver/material_template.spec.js
resfulservice/spec/mocks/curationMock.js
resfulservice/spec/mocks/index.js
resfulservice/src/controllers/authController.js
resfulservice/src/controllers/curationController.js
resfulservice/src/graphql/resolver/material_template/mutation.js
resfulservice/src/middlewares/validations.js
resfulservice/src/models/curatedObject.js
resfulservice/src/routes/curation.js
resfulservice/src/server.js
resfulservice/src/utils/xlsxFileManager.js

This task enables ingesting the latest master template spreadsheet, processing it, and converting it into XML.
1. Define new routes for new uploads, update existing submissions, fetch a list of submissions, and fetch a single submission
2. Write new controllers for each of the above endpoints
3. Define mongoDB schema for xlsx curation
4. Generate a JSON response object for FE based on user spreadsheet submission
5. Write a test coverage for these new endpoints
closes #375

feat(#375): Spreadsheet curation logic

---

app/src/components/explorer/Pagination.vue
app/src/mixins/explorerQueryParams.js
app/src/pages/explorer/Gallery.vue
app/src/pages/explorer/image/Image.vue
app/src/pages/explorer/xml/Xml.vue

Enables going back to the same search results for XMLs and charts
I tried as much as possible to migrate out the existing logic from both images and XML into a single mixin (explorerQueryParams.js)
- Some code was duplicated between images and XML, tried to standardize these
- Some code was a little too customized for the search method, so left those in their original components
- Charts use a different query method than XMLs and images, so that one only uses page number and not the other params
There was also a bug in Pagination.vue where the UI for the selected page number wouldn't update if the prop was externally modified by bypassing its internal methods, so this PR fixes that
closes #403

feat(#403): Add and fix url query params for XML and chart search

---

app/src/pages/explorer/dataset/Dataset.vue
app/src/router/module/explorer.js
app/src/store/modules/explorer/actions.js

- Fixes loading spinner
-  Loads datasets that don’t have complete data (specifically malformed ORCID)
-  For distribution list, shows label (shorter name) instead of full link
-  Renames to Dataset.vue since has its own folder
-  Shows "Click to download" file for distributions like in XML gallery
-  Centers date on metadata page
-  Replaces image alt with Title and "Image"
closes #417

Dataset UI updates for SDD results page

---

app/src/assets/css/modules/_resetvuematerial.scss
app/src/components/Drawer.vue
app/src/components/accordion.vue
app/src/components/explorer/Header.vue
app/src/components/nanomine/PageHeader.vue
app/src/pages/explorer/Tools.vue
app/src/pages/explorer/tools/ToolsBase.vue
app/src/pages/explorer/tools/dynamfit/DynamFit.vue
app/src/pages/nanomine/tools/Polymerizer.vue
app/src/router/module/explorer.js
app/tests/unit/components/explorer/Header.spec.js
app/tests/unit/pages/explorer/Tools.spec.js

This ticket creates a new Tools homepage in Explorer to match updated UI styling
- Updates links in drawer and page header
- Creates an empty template page for the new DynamFit tool migration
- Removes links to Polymerizer tool (currently unavailable)
closes #428

#428 update tools page

---

app/src/assets/css/modules/_misc.scss
app/src/assets/css/modules/_utility.scss
app/src/components/nanomine/PageHeader.vue
app/src/pages/nanomine/conferences/CSSI2023.vue
app/src/pages/nanomine/conferences/MRS2022.vue
app/src/router/module/nanomine.js

This task creates a landing page for the QR code that will go on the poster for the CSSI PI meeting. 
It also replaces the old "MRS2022" tab with a new "Conferences" tab. The links that were previously in the old tab are now on a separate MRS 2022 page.
Both new conference pages (MRS 2022, CSSI 2023) contain relevant links for the conference materials. The CSSI 2023 page lists all publications (along with their DOI links) from the annual report. 
NOTE: as of opening this PR, I haven't yet added a virtual poster link, so that will need to be updated whenever it's available
closes #443

feat(#443): create QR code landing page

---

app/src/pages/nanomine/conferences/CSSI2023.vue
app/tests/unit/pages/nanomine/conferences/cssi2023.spec.js

We previously didn't have a [link to the CSSI PI meeting virtual poster]( https://doi.org/10.6084/m9.figshare.24201960.v1) on the QR code landing page. This ticket updates the link (and relevant unit tests)
closes #445

feat(#445): Update virtual poster link

---

app/src/pages/nanomine/tools/chemProps/chemProps.html

The text on the ChemProps page was modified with the following updates:
1. Set the font-size to 1.4rem for all text on the page.
2. Adjusted the line-height to 1.5 for all text on the page.
3. Changed the color of the link text in the ChemProps description section to primary color.
4. Updated the color of the "Request Token" button to primary color.

Chemprops Page Fix
