Duke-MatSci/materialsmine

whyis/Dockerfile
whyis/Dockerfile.dev
whyis/docker-compose.yml

#8: Added container to whyis

---

.gitignore
app/.editorconfig
app/.eslintrc.js
app/.eslintrc.json
app/.gitignore
app/Dockerfile.dev
app/babel.config.js
app/docker-compose.yml
app/jest.config.js
app/package-lock.json
app/package.json
app/public/index.html
app/src/App.vue
app/src/components/HelloWorld.vue
app/src/main.js
app/src/pages/About.vue
app/src/pages/Home.vue
app/src/registerServiceWorker.js
app/src/router/index.js
app/src/store/index.js
app/src/store/modules/auth/actions.js
app/src/store/modules/auth/getters.js
app/src/store/modules/auth/index.js
app/src/store/modules/auth/mutations.js
app/tests/unit/example.spec.js
app/vue.config.js
package.json

#33 downgrade from vue3 to vue2

---

.github/workflows/ci.yml
.husky/pre-push
app/tests/unit/example.spec.js
package.json

feat(#37): Create pr workflow

---

.github/workflows/ci.yml
README.md

feat(#38): Post merge request workflow

---

README.md

#69: Update README for Windows users' additional Docker steps

---

.github/workflows/ci.yml

fix(#55): Added frontend build

---

.github/workflows/ci.yml

fix(#56): Updated CI with proxy build workflow

---

docker-compose.git.yml
docker-compose.yml
resfulservice/misc/envVarFile.gpg
resfulservice/package.json
resfulservice/spec/middlewares/isAuth.spec.js
resfulservice/src/graphql/index.js
resfulservice/src/graphql/schema.js
resfulservice/src/middlewares/accept.js
resfulservice/src/middlewares/fileStorage.js
resfulservice/src/middlewares/isAuth.js
resfulservice/src/middlewares/parseEnv.js
resfulservice/src/server.js
resfulservice/src/utils/jwtService.js

Note: The additional environment variable is a breaking change and will trigger an error if gpg file is not updated
- Add auth validation middleware service
- Move file service into its own middleware
- Added additional environment variable
close #84

feat(#84): Create validation service - Restful

---

app/src/assets/css/modules/_pages.scss
app/src/components/explorer/Header.vue
app/src/components/explorer/SearchHeader.vue
app/src/pages/explorer/Home.vue
app/src/store/modules/explorer/getters.js
app/src/store/modules/explorer/index.js
app/src/store/modules/explorer/mutations.js
app/tests/unit/components/explorer/SearchHeader.spec.js

Tabs for search results
- Created the tab component that should seat atop results
- Tab for articles, samples, images, charts, and materials are available
- Moved the input field beside avatar into the new header tab component
- Started setting up Vuex for managing tab/result state
Close #97

#97 Header Tab Panel

---

app/src/pages/explorer/Gallery.vue
app/src/store/modules/explorer/gallery/getters.js
app/src/store/modules/explorer/gallery/index.js
app/src/store/modules/explorer/gallery/mutations.js

Ran linter, cleaned up files.
Fix #130

#130: Linting fix

---

app/src/components/nanomine/PageHeader.vue

closes #172 
This is a temporary menu item added for the MRS 2022 Tutorial. Can remove some time after June 8th.

Add menu item MRS2022 to PageHeader.vue

---

app/src/assets/css/modules/_navigation.scss
app/src/assets/css/modules/_visualize.scss

fix #163: z-index dropdown

---

app/src/pages/explorer/parameterized-query/templates/PQ01A.ttl
app/src/pages/explorer/parameterized-query/templates/index.js

#175: add two-property parameterized query

---

app/src/components/nanomine/PageHeader.vue

#179: Fix dropdown links for galleries

---

resfulservice/package.json
resfulservice/spec/graphql/resolver/contact.spec.js
resfulservice/spec/graphql/resolver/user.spec.js
resfulservice/spec/graphql/schema/contact.spec.js
resfulservice/src/graphql/resolver/contact/input.graphql
resfulservice/src/graphql/resolver/contact/mutation.js
resfulservice/src/graphql/resolver/contact/query.js
resfulservice/src/graphql/resolver/contact/type.graphql
resfulservice/src/graphql/resolver/index.js
resfulservice/src/graphql/resolver/user/mutation.js
resfulservice/src/graphql/resolver/user/query.js
resfulservice/src/graphql/schema.graphql
resfulservice/src/models/contact.js
resfulservice/src/utils/errorFormater.js

Consume contact page submitted data
Retrieve all contact page info submitted for the admin user.
Allow date filter of contact request
closes #238

feat(#238): Contact us page api

---

.github/workflows/ci.yml
.gitignore
docker-compose.git.yml
docker-compose.yml
mockDB/fuseki/configuration/admin.ttl
mockDB/fuseki/configuration/knowledge.ttl
nginx/default.conf
resfulservice/misc/decryptENVARFile.sh
whyis/Dockerfile
whyis/docker-compose.yml
whyis/materialsmine/system.conf

The first of 8 part process to deploy and integrate Whyis with the rest of the MaterialsMine Application.
***NO NEED FOR REVIEW****
For questions on any specific part of WHYIS, reach out to [Jamie](mccusj2@rpi.edu)

Whyis Integration 1 of 8

---

app/Dockerfile
app/Dockerfile.dev
app/src/assets/css/modules/_form.scss
app/src/pages/explorer/Curate.vue
app/src/pages/explorer/image/Image.vue
app/src/pages/explorer/image/ImageDetailView.vue
app/tests/unit/pages/explorer/Image.spec.js
app/tests/unit/pages/explorer/ImageDetailView.spec.js
app/tests/unit/pages/explorer/Visualization.spec.js
app/tests/unit/pages/explorer/__snapshots__/Image.spec.js.snap
resfulservice/Dockerfile
resfulservice/Dockerfile.dev

Refactor image gallery
closes #236

fix(#236): Update image gallery search

---

app/src/assets/css/modules/_navigation.scss
app/src/assets/css/modules/_section.scss
app/src/assets/css/modules/_utility.scss
app/src/components/Drawer.vue
app/src/components/nanomine/PageHeader.vue

- Fixed the header responsiveness for both home page and about pages
- Fixed the menu alignment for small screens
- Changed the xml upload link to redirect to prod
close #250

#250: UI fixes for demo

---

.github/CODEOWNERS
app/Dockerfile
app/src/pages/nanomine/tools/dynamfitTool/dynamfit.js
app/src/store/modules/explorer/actions.js
resfulservice/package.json
resfulservice/spec/graphql/resolver/pixelated.spec.js
resfulservice/spec/graphql/schema/pixelated.spec.js
resfulservice/src/controllers/pixelatedController.js
resfulservice/src/graphql/resolver/pixelated/query.js
resfulservice/src/graphql/resolver/pixelated/type.graphql
resfulservice/src/middlewares/fileStorage.js
resfulservice/src/middlewares/isAuth.js
resfulservice/src/routes/pixelated.js
resfulservice/src/server.js

@jpmccu I removed @stouffers from code reviewers. This merge will resolve it
closes #252

feat(#252): Add resolver for pixelated data and updated unit test

---

app/src/assets/css/modules/_navigation.scss
app/src/pages/metamine/Base.vue

- Replaced the current version of QA's mm header menus with ones more like what's on the main homepage
- Fixed the font color, hover background color
- Added dropdown menus 
- Added menu link to #241 
close #261

#261: Fix MetaMine header styling and add viz link

---

resfulservice/src/graphql/resolver/dataset/type.graphql
resfulservice/src/middlewares/loggerService.js
resfulservice/src/routes/pixelated.js

This update automatically creates file storage at deploy

Fix (#252): Updates

---

resfulservice/src/middlewares/validations.js
resfulservice/src/routes/files.js

🚨 Fix curation upload bug issues

#229: Fix curation upload route issues

---

resfulservice/src/controllers/fileController.js
resfulservice/src/middlewares/validations.js
resfulservice/src/routes/files.js

Refactored Upload file API endpoint

#229 fix upload

---

resfulservice/spec/graphql/resolver/dataset.spec.js
resfulservice/spec/graphql/schema/dataset.spec.js
resfulservice/src/controllers/adminController.js
resfulservice/src/controllers/fileController.js
resfulservice/src/controllers/kgWrapperController.js
resfulservice/src/controllers/loginController.js
resfulservice/src/controllers/pixelatedController.js
resfulservice/src/controllers/searchController.js
resfulservice/src/controllers/test.js
resfulservice/src/graphql/resolver/dataset/input.graphql
resfulservice/src/graphql/resolver/dataset/mutation.js
resfulservice/src/graphql/resolver/dataset/query.js
resfulservice/src/graphql/resolver/dataset/type.graphql
resfulservice/src/graphql/transformer/datasets.js
resfulservice/src/models/user.js

Fix data issues on BE for dataset curation.

[Hotfix]: Dataset curation updates

---

app/src/assets/css/modules/_form.scss
app/src/components/nanomine/ImageUpload.vue
app/src/modules/gql/contact-gql.js
app/src/pages/explorer/Gallery.vue
app/src/pages/metamine/Base.vue
app/src/pages/nanomine/contactus/contactus.html
app/src/pages/nanomine/contactus/contactus.js
app/tests/unit/pages/explorer/Home.spec.js
app/tests/unit/pages/nanomine/contactus.spec.js
resfulservice/spec/graphql/resolver/dataset.spec.js

Integrated BE with the contact page for both Metamine and Nanomine. All submission goes to the DB. This task will require an additional ticket to create a UI rendering for all inquiries.
closes #279

[MINOR]: #279 contact page BE integration

---

.gitignore
README.md
app/src/assets/css/modules/_resetvuematerial.scss
app/src/assets/css/modules/_visualize.scss
app/src/components/accordion.vue
app/src/pages/explorer/Visualization.vue
app/src/pages/explorer/parameterized-query/parameterized-query-page.vue
app/src/pages/nanomine/Base.vue
app/tests/unit/pages/explorer/Visualization.spec.js
resfulservice/src/controllers/invalidController.js
resfulservice/src/graphql/resolver/imageExplorer/input.graphql
resfulservice/src/graphql/resolver/imageExplorer/query.js
resfulservice/src/graphql/resolver/imageExplorer/type.graphql
resfulservice/src/middlewares/isAuth.js
resfulservice/src/pipelines/image-pipeline.js
resfulservice/src/routes/invalid.js
resfulservice/src/server.js

1. Fixed header disappears on user scroll behavior. 
2. Add additional filter for image search - filter by DOI and filter by Microscopy type
3. Removed undefined from image search and image gql response
4. Refactor/update parameterize page UI for consistency
5. Fix the visualization page mobile view bug
6. Add 404 error handler for back-end unavailable routes
closes #293

#293 UI & BE Enhancements

---

resfulservice/src/pipelines/image-pipeline.js

- Fixed remaining undefined issue as a result of curation defect
- Fix keyword image search
- Image gallery search enhancements

🔥 #293: Image Pipeline Hot fix

---

resfulservice/src/graphql/resolver/imageExplorer/type.graphql
resfulservice/src/graphql/transformer/index.js
resfulservice/src/pipelines/image-pipeline.js

This PR contains the following:
- Image schema updates to add `sampleID`
- Image transformer updates to add `sampleID`
- Refactor image query pipeline

#293: Image pipeline, image schema updates and refactoring

---

app/Dockerfile
app/Dockerfile.dev
app/package-lock.json

This update fixes CI build failure for the FE app

CI: Fixes for build failure

---

.github/workflows/ci.yml
.github/workflows/prodBuilder.yml
.github/workflows/prodci.yml
.gitignore
docker-compose.test.git.yml
package.json
release.config.js
resfulservice/.nycrc.json
resfulservice/package.json
resfulservice/spec/common/utils.js
resfulservice/spec/logger.js
resfulservice/spec/middlewares/isAuth.spec.js
resfulservice/spec/middlewares/isInternal.spec.js

BREAKING CHANGE: Added the prod CI pipeline, versioning, and release
In addition, this ticket also covers:
- Add prod CI
- Build versioning and tagging
closes #309

Feat(#309): Prod CICD

---

.github/workflows/prodBuilder.yml
.github/workflows/prodci.yml

fix(ci/cd): Fix failing prod pipeline

---

.github/workflows/prodci.yml

fix(ci/cd): Fix failing pipeline

---

.github/workflows/ci.yml
.github/workflows/prodBuilder.yml
.github/workflows/prodci.yml

fix(ci/cd): Pipeline failure fix

---

.github/workflows/ci.yml
.github/workflows/prodBuilder.yml
.github/workflows/prodci.yml

This fix removes the deprecated marcofaggian/action-download-multiple-artifacts@v1. Now updated to use the latest version.

fix(ci/cd): Failing asset artifact download

---

.github/workflows/prodci.yml
package.json

Update to fix the release step in the workflow. Failing initially due to incorrect token

fix(CI/CD): Pipeline failure

---

.github/workflows/ci.yml
.github/workflows/prodBuilder.yml
.github/workflows/prodci.yml

This fixes docker image build failures

build(CI/CD): 🔥Fix pipeline

---

.github/workflows/prodci.yml

Fix and test automated tagging in CI workflow

Fix(CI/CD): Prod build fixes

---

.github/workflows/prodci.yml

Fix automated tagging in CI workflow for docker images

fix(CI/CD): Docker image tagging fixes

---

.github/workflows/prodBuilder.yml

This fix removes piping from docker image tagging in the CI workflow

feat(CI/CD): Remove pipe fix

---

.github/workflows/prodci.yml

Renaming docker built docker image and append tags

fix(CI/CD): Rename docker image builds

---

.github/workflows/prodci.yml
release.config.js

Fix (CI/CD): Trigger new or latest version

---

whyis/materialsmine/materialsmine/__init__.py
whyis/materialsmine/materialsmine/semantic_scholar.py
whyis/materialsmine/whyis.conf

completed abstract annotator

---

README.md

Lists the main steps for contributing to the repo with relevant links. Let me know if I'm forgetting anything
closes #368

docs(#368): add contribution guidelines to README

---

resfulservice/.gitignore
resfulservice/config/xlsx.json
resfulservice/spec/controllers/curationController.spec.js
resfulservice/spec/mocks/curationMock.js
resfulservice/src/controllers/curationController.js
resfulservice/src/middlewares/fileStorage.js
resfulservice/src/routes/curation.js

This task enables partial stepper objects retrieval needed to generate UI stepper form
closes #385

feat(#385): xlsx curation - 2

---

README.md
app/src/router/index.js
resfulservice/config/constant.js

- Added Edge to list of supported browsers
- Made `beforeEach` re-route either back to the current route or to home depending on use case
- Added links to our testing libraries in the README
fixes #398 
closes #396 
closes #288

#398 authentication bugs

---

app/src/assets/css/modules/_visualize.scss
app/src/pages/explorer/image/Image.vue
app/src/pages/explorer/image/ImageDetailView.vue
app/src/pages/metamine/Home.vue
resfulservice/src/graphql/resolver/imageExplorer/input.graphql
resfulservice/src/graphql/resolver/imageExplorer/query.js
resfulservice/src/graphql/transformer/index.js
resfulservice/src/pipelines/image-pipeline.js

This update expands the image filter options, updates the image gallery UI, and expands the image gallery query pipeline.
closes #413

#413 Image Filter Enhancements

---

app/src/modules/whyis-dataset.js
nginx/default.conf
resfulservice/config/constant.js
resfulservice/config/xlsx.json
resfulservice/package.json
resfulservice/spec/controllers/curationController.spec.js
resfulservice/spec/controllers/fileController.spec.js
resfulservice/spec/graphql/resolver/xml.spec.js
resfulservice/spec/mocks/curationMock.js
resfulservice/spec/utils/fileManager.spec.js
resfulservice/src/api-docs/swagger-service.yaml
resfulservice/src/controllers/curationController.js
resfulservice/src/controllers/fileController.js
resfulservice/src/graphql/resolver/xml/input.graphql
resfulservice/src/graphql/resolver/xml/query.js
resfulservice/src/graphql/resolver/xml/type.graphql
resfulservice/src/routes/curation.js
resfulservice/src/utils/curation-utility.js
resfulservice/src/utils/fileManager.js

- Fix file response link
- Added curation status for xml
- Update unit test
- Dynamic xsd schema generation

feat(none): backend updates and fixes

---

app/src/pages/nanomine/conferences/CSSI2023.vue
app/tests/unit/pages/nanomine/conferences/cssi2023.spec.js
app/tests/unit/pages/nanomine/conferences/mrs2022.spec.js

This ticket is an update to PR #444 . 
- Adds 3 additional publications (two of which don't yet have DOIs)
- Creates unit tests for both conference pages
Note: The commit message tags the wrong issue, should be #443 instead of 433

feat(#443): Update CSSI2023 landing page and add unit tests

---

.github/workflows/prodci.yml

Adding managed services workflow the prod CI pipeline
closes #469

✨feat(#469): Adding managed services workflow the prod CI pipeline

---

resfulservice/src/controllers/kgWrapperController.js

Added missing req param for getAllChart function

Fix(#472): Bug fix

---

resfulservice/src/controllers/adminController.js
resfulservice/src/controllers/curationController.js
resfulservice/src/controllers/kgWrapperController.js
resfulservice/src/controllers/searchController.js

Adding fixes to functions missing request params on BE

Refactoring ECS

---

app/src/components/explorer/dynamfit/ChartSetting.vue
resfulservice/src/middlewares/validations.js
resfulservice/src/pipelines/curation-pipeline.js

This change prioritizes `control ID` in the database query pipeline over `title` for Xml thumbnail and title. This is to conform with existing/old Xml curations

Fix: Show control ID for xml thumbnails

---

.gitignore
app/src/components/ChartGallery.vue
app/src/components/LoginRequired.vue
app/src/components/nanomine/HeroHeader.vue
app/src/modules/vega-chart.js
app/src/pages/explorer/Curate.vue
app/src/pages/explorer/chart/editor/Chart.vue
app/src/pages/explorer/curate/xml/xmlUpload.vue
app/src/pages/explorer/xml/XmlLoader.vue
app/src/router/module/explorer.js
app/src/store/modules/explorer/curation/actions.js
app/tests/unit/components/nanomine/heroheader.spec.js
resfulservice/spec/controllers/curationController.spec.js
resfulservice/spec/graphql/resolver/user.spec.js
resfulservice/src/controllers/curationController.js
resfulservice/src/graphql/resolver/user/mutation.js
resfulservice/src/middlewares/fileStorage.js
resfulservice/src/routes/curation.js
resfulservice/src/server.js

This implementation updates the /explorer/curate page, creating a new page for XML input, adding a new endpoint and controller logic on the backend to process and validate the submission, and ensuring the new functionality is covered by tests.

XML Curation

---

app/src/pages/ns/Home.vue
app/src/router/index.js
app/src/router/module/explorer.js
app/src/router/module/ns.js
resfulservice/spec/controllers/curationController.spec.js
resfulservice/spec/graphql/resolver/comment.spec.js
resfulservice/spec/graphql/resolver/contact.spec.js
resfulservice/spec/graphql/resolver/dataset.spec.js
resfulservice/spec/graphql/resolver/material_template.spec.js
resfulservice/spec/graphql/resolver/pixelated.spec.js
resfulservice/spec/graphql/resolver/xml.spec.js
resfulservice/spec/mocks/graphqlMock.js
resfulservice/spec/mocks/index.js

Iinitial contribution for namespace page resolver

Resolve Namespace - Pt1

---

app/src/modules/whyis-dataset.js
app/src/pages/explorer/curate/sdd/SddForm.vue
app/src/pages/explorer/curate/sdd/SddLinking.vue
app/src/pages/explorer/dataset/Dataset.vue
app/src/pages/explorer/dataset/DatasetGallery.vue
app/src/pages/explorer/xml/YamlLoader.vue
app/src/router/index.js
app/src/store/modules/explorer/curation/actions.js
app/src/store/modules/misc/getters.js
app/src/store/modules/misc/index.js
app/src/store/modules/misc/mutations.js
app/tests/unit/components/metamineNU/VisualizationLayout.spec.js
docker-compose.yml
resfulservice/spec/sw/utils/worker-service.spec.js
resfulservice/spec/utils/logWriter.spec.js

FEAT(#508): Linter and test fixes

---

.github/workflows/ci.yml
app/src/pages/explorer/curate/sdd/SddForm.vue
app/src/pages/explorer/dataset/Dataset.vue
app/src/pages/explorer/dataset/DatasetGallery.vue
app/src/router/index.js
app/src/store/modules/explorer/curation/actions.js
app/src/store/modules/misc/getters.js
app/src/store/modules/misc/index.js
app/src/store/modules/misc/mutations.js

- Dataset curation fixes
- Dataset gallery updates
- GH workflow updates
- Delete dataset distribution after removal from KG
- Capturing route info

FEAT(#508): Dataset Fixes

---

LICENSE

FEAT(#6) Adding License
